# Generated by Django 2.1.5 on 2019-01-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190126_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Membership', to='groups.Person'),
        ),
    ]
